#!/usr/bin/python/

import sys
import os

def add_spaces(string, newlen, dir = 0):
    if len(string) > newlen:
        return string

    fill = newlen - len(string)
    if dir == 0:
        for i in range(fill):
            string = string + ' '

    else:
        for i in range(fill):
            string = ' ' + string

    return string


def usage():
    print 'Script to read in two files generated by Liz Kellog\'s fix_bb_monomer_ddg executable, get the ddg Values fore ach mutation and also substract the ones in the second file from the ones in the first file ',
    print 'Usage: Substract2LizDdgOutputs.py -f1 <file1> -f2 <file2>'


def read_file_to_commentless_linelist( filehandle ):
    
    return_lines = []
    line = filehandle.readline()
    while( line ):
        
        commentpos = line.find('#')
        if commentpos != -1:
            if line[commentpos-1:commentpos] != "\\":
                #print "splitting out comment %s" % line[commentpos:]
                line = line[0:commentpos]

        if len(line) > 0 :
            return_lines.append(line)

        line = filehandle.readline()

    return return_lines


CommandArgs = sys.argv[1:]
if len(CommandArgs) < 2:
    usage()
    sys.exit()

mutnamecolumn = 1
ddg_column = 2
mutfile1_ddgs = []
mutfile2_dict = {}
filename1 = ''
filename2 = ''
outlines = []


for arg in CommandArgs:
    if arg == '-f1':
        filename1 = CommandArgs[CommandArgs.index(arg)+1]
    if arg == '-f2':
        filename2 = CommandArgs[CommandArgs.index(arg)+1]
    elif arg == '-help':
        usage()
        sys.exit()

outlines.append("Mutation    ddG_"+filename1+"      ddG_"+filename2+"          diff_ddG")


file1 = open(filename1,'r')
file1lines = read_file_to_commentless_linelist( file1 )
file1.close()

file2 = open(filename2,'r')
file2lines = read_file_to_commentless_linelist( file2 )
file2.close()

for line in file2lines:
    line_items = line.split()
    if len( line_items ) < 2:
        continue
    mutfile2_dict[ line_items[mutnamecolumn] ] = line_items[ ddg_column ]

#print str( len( mutfile2_dict ) ) + " mutations were found in " + filename2

for line in file1lines:
    line_items = line.split()
    if len( line_items ) < 2:
        continue
    this_mutation = line_items[ mutnamecolumn ]
    if mutfile2_dict.has_key( this_mutation ):
        #print line_items[ddg_column]
        #print mutfile2_dict[ this_mutation ]
        this_diff = float(line_items[ddg_column]) - float(mutfile2_dict[ this_mutation ])
        outlines.append( this_mutation + "     " + line_items[ddg_column] + "     " + mutfile2_dict[ this_mutation ] + "        " + str( this_diff  ) )
    else:
        print "Mutation " + this_mutation + " in file 1 not found in file2."

                         
for outline in outlines:
    print outline


                
